In [1]:
import numpy as np


In [2]:
import numpy as np
def lesser ():
  if (n1.shape==n2.shape):
    return n1<n2

def lesser_equal ():
  if (n1.shape==n2.shape):
    return n1<=n2

def greater():
  if (n1.shape==n2.shape):
    return n1>n2

def greater_equal():
  if (n1.shape==n2.shape):
    return n1>=n2

n1=np.array([[5,3,88],[4,6,81]])

n2=np.array([[5,4,58],[20,6,58]])
print("The number is lesser numbers",lesser())
print("The number is lesser_equal numbers",lesser_equal())
print("The number is greater numbers",greater())
print("The number is greater_equal numbers",greater_equal())

The number is lesser numbers [[False  True False]
 [ True False False]]
The number is lesser_equal numbers [[ True  True False]
 [ True  True False]]
The number is greater numbers [[False False  True]
 [False False  True]]
The number is greater_equal numbers [[ True False  True]
 [False  True  True]]


In [3]:
a=abc=np.zeros((2,5))
b=abx=np.ones((2,5))
c=abs=np.full((2,5),10)
print(a)
print(b)
print()

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]



In [4]:
n4=np.array([[4,3,5],[2,6,7],[3,4,8]])
print("Original array:\n",n4)
print("Sum of all elements:\n",np.sum(n4))
print("Sum of each column:\n",np.sum( n4, axis=0))
print("Sum of each row:\n",np.sum(n4, axis=1))



Original array:
 [[4 3 5]
 [2 6 7]
 [3 4 8]]
Sum of all elements:
 42
Sum of each column:
 [ 9 13 20]
Sum of each row:
 [12 15 15]


In [5]:
n4=np.array([[4,3,5],[2,6,7],[3,4,8]])
print("Original array:\n",n4)
print("Sum of all elements:\n",np.sum(n4))
print("Sum of each column:\n",np.sum( n4, axis=0))
print("Sum of each row:\n",np.sum(n4, axis=1))



Original array:
 [[4 3 5]
 [2 6 7]
 [3 4 8]]
Sum of all elements:
 42
Sum of each column:
 [ 9 13 20]
Sum of each row:
 [12 15 15]


In [6]:
n8=np.array([[89,85,65],
                [66,55,27]])
print("Trigonometric Sine of n8 is:",np.sin(n8))
print("Trigonometric Cosine of n8 is:",np.cos(n8))
print("Trigonometric Tangent of n8 is:",np.tan(n8))

Trigonometric Sine of n8 is: [[ 0.86006941 -0.17607562  0.82682868]
 [-0.02655115 -0.99975517  0.95637593]]
Trigonometric Cosine of n8 is: [[ 0.51017704 -0.98437664 -0.56245385]
 [-0.99964746  0.02212676 -0.29213881]]
Trigonometric Tangent of n8 is: [[ 1.68582537e+00  1.78870172e-01 -1.47003826e+00]
 [ 2.65605178e-02 -4.51830879e+01 -3.27370380e+00]]
